name: Run all tests
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  pre_steps:
    # Allow to cancel pending workflows if you commit multiple times, for instance.
    # Pretty useful to save GH Actions minutes.
    name: Skip if duplicate action
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true

  run-all-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Comment trigger
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/run-all-tests"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run frontend tests
        uses: benc-uk/workflow-dispatch@v1
        if: steps.check.outputs.triggered == 'true'
        with:
          workflow: Frontend Tests
          token: ${{ secrets.SUPER_SECRET }}
